### ISSUE TITLE
Inconsistency of the font styling in the FAQ's section 

### ISSUE THREAD

**Issue by PranitPatil03** [notaryproject/notaryproject.dev#232] opened 2023-05-20 18:38 UTC
In the FAQ section, some questions are missing the "Font Bold" property, which seems unintentional. Please refer to the screenshots for clarification.

Link: https://notaryproject.dev/docs/faq/

<details><summary>The questions having font bold property</summary>
<p>

<img width="960" alt="Screenshot 2023-05-21 000451" src="https://github.com/notaryproject/notaryproject.dev/assets/91155068/9ae14b2d-d3f5-47fa-985d-92f5533ec854">

</p>
</details> 

<details><summary>The questions does not have font bold property</summary>
<p>
<img width="960" alt="Screenshot 2023-05-21 000652" src="https://github.com/notaryproject/notaryproject.dev/assets/91155068/feb5f1f6-4a1e-4ae2-92bd-d280c5877486">

</p>
</details> 

Currently working on this 🙌

**Comment by PranitPatil03** [comment] 2023-05-21 12:45
Hey @Aryan20 

Your solution and changes are great. However, before working on any issues, please check if someone else is already working on them. This will save time for other contributors.🙌

**Comment by Aryan20** [comment] 2023-05-21 14:15
Hey @PranitPatil03 !
Thanks! Also, although I do agree with your point, I would like to point out that at the time of solving the issue, there were no indicators that others might be working on it.

After contributing to open source for a few years, the general strategy I utilise is (among many other people) -
1) If the issue has no comments and no pointers that someone is working on it, can be done fast, and is most likely a real bug, just solve and open PR.
2) If the issue has someone assigned to it, and it takes about a minute to solve, but the assignee hasn't replied for more than a week, you can most likely create a PR (Keeping some other factors in mind as well).
3) If the issue is long and will take quite some days to solve, and someone else also might begin the work in the meantime, then mention that in a comment and get the issue assigned.

I'm sorry if you were working on it. Happy bug fixing :)

**Closed** 2023-07-14 16:43 UTC
