### ISSUE TITLE
The Sha256's value exceeds the width in the mobile view

### ISSUE THREAD

**Issue by PranitPatil03** [notaryproject/notaryproject.dev#230] opened 2023-05-20 12:04 UTC
Issue: The value of the SHA256 in the provided example is overrunning the maximum width of the page. Please refer to the attached screenshot for further information.

Link: https://notaryproject.dev/docs/tutorials/trust-policy/

<details><summary>SS</summary>
<p>

<img width="190" alt="Screenshot 2023-05-20 172155" src="https://github.com/notaryproject/notaryproject.dev/assets/91155068/8e9411b2-cbee-4f0a-a0e2-072c4a64d0ef">

</p>
</details> 

Currently working on this 🙌

**Comment by PranitPatil03** [comment] 2023-05-21 12:46
hey @Aryan20

Your solution and changes are great. However, before working on any issues, please check if someone else is already working on them. This will save time for other contributors.🙌

**Comment by Aryan20** [comment] 2023-05-21 14:16
Hey @PranitPatil03 !
Thanks! Also, although I do agree with your point, I would like to point out that at the time of solving the issue, there were no indicators that others might be working on it.

After contributing to open source for a few years, the general strategy I utilise is (among many other people) -
1) If the issue has no comments and no pointers that someone is working on it, can be done fast, and is most likely a real bug, just solve and open PR.
2) If the issue has someone assigned to it, and it takes about a minute to solve, but the assignee hasn't replied for more than a week, you can most likely create a PR (Keeping some other factors in mind as well).
3) If the issue is long and will take quite some days to solve, and someone else also might begin the work in the meantime, then mention that in a comment and get the issue assigned.

I'm sorry if you were working on it. Happy bug fixing :)

**Closed** 2023-07-14 19:05 UTC
